version: '2'

services:
  bootstrap:
    build: .
    container_name: bootstrap
    entrypoint: /root/files/start_bootstrap.sh
    command: '--addr ":30304" --nodekeyhex 091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322'
    networks:
      - backendnet
    ports:
      - "30304:30304"
      - "30304:30304/udp"
      - "8546:8546"

  quorum_node:
    build: .
    entrypoint: /root/files/start_eth_node.sh
    networks:
      - backendnet
    command: '--datadir=~/.ethereum/devchain --verbosity "3" --voteaccount 0x007ccffb7916f37f7aeef05e8096ecfbe55afc2f --votepassword 123 --blockmakeraccount 0x007ccffb7916f37f7aeef05e8096ecfbe55afc2f --blockmakerpassword 123 --rpc --port 30304 --autodag --rpcport 8547 --rpccorsdomain="http://127.0.0.1:8547" --networkid=456719 --rpc --rpcapi "db,personal,eth,net,web3,miner,admin,quorum" --bootnodes "enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@IPAddress:30304"'
    stdin_open: true
    tty: true
    environment:
      TARGET_HOSTNAME: ${HOSTNAME}


  quorum_contract_deployer:
    build: .
    entrypoint: /root/files/start_eth_contract_deployer.sh
    networks:
      - backendnet
    command: '--datadir=~/.ethereum/devchain --verbosity "2" --rpc --port 30304 --rpcport 8547 --rpccorsdomain="http://127.0.0.1:8547" --networkid=456719 --rpc --rpcapi "db,personal,eth,net,web3,miner,admin,quorum" --bootnodes "enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@IPAddress:30304"'
    stdin_open: true
    tty: true
    ports:
      - "40000"
      - "20000:20000"
    environment:
      TARGET_HOSTNAME: ${HOSTNAME}

networks:
  backendnet:
